// src/redux/slice/map/index.ts
import { createSlice, PayloadAction } from "@reduxjs/toolkit";

// Define the shape of your ArcGIS Map and MapView instances
// Using 'any' as a placeholder for now, ideally you'd import
// actual types from @arcgis/core if you set up your environment for them.
interface EsriMapInstance {
  map: any;
  view: any;
}

interface MapState {
  mapInstance: EsriMapInstance | null;
}

const initialState: MapState = {
  mapInstance: null,
};

const mapSlice = createSlice({
  name: "map",
  initialState,
  reducers: {
    // This reducer sets the mapInstance in the state
    setMapInstance: (state, action: PayloadAction<EsriMapInstance | null>) => {
      state.mapInstance = action.payload;
    },
  },
});

// Export the action creator generated by createSlice using named export
export const { setMapInstance } = mapSlice.actions;

// Export the reducer as the default export
export default mapSlice.reducer;